[environment]
cpu_count = 4
exec_env = "singularity"
free_mem = 4.5
overcommit_policy = "heuristic"
overcommit_limit = "50%"
nipype_version = "1.8.6"
templateflow_version = "23.1.0"
total_memory = 11.446575164794922
version = "1"

[execution]
ants_float = false
bids_dir = "/home/joe/mriqc_space/sub-C001/anat"
bids_database_dir = "/home/joe/mriqc_space/mriqc23.1.0rc0/work/20231115-181031_9903be04-a18a-436a-b454-83ebcdcc3de2/bids_db"
cwd = "/home/joe/mriqc_space/mriqc23.1.0rc0"
debug = false
dry_run = false
dsname = "<unset>"
float32 = true
layout = "BIDS Layout: .../joe/mriqc_space/sub-C001/anat | Subjects: 1 | Sessions: 0 | Runs: 1"
log_dir = "/home/joe/mriqc_space/out/logs"
log_level = 25
no_sub = true
notrack = false
output_dir = "/home/joe/mriqc_space/out"
participant_label = [ "C001",]
pdb = false
reports_only = false
resource_monitor = false
run_uuid = "20231115-181031_9903be04-a18a-436a-b454-83ebcdcc3de2"
templateflow_home = "/home/joe/.cache/templateflow"
upload_strict = false
verbose_reports = false
webapi_token = "<secret_token>"
webapi_url = "https://mriqc.nimh.nih.gov:443/api/v1"
work_dir = "/home/joe/mriqc_space/mriqc23.1.0rc0/work"
write_graph = false

[workflow]
analysis_level = [ "participant",]
biggest_file_gb = 0.0038583064451813698
deoblique = false
despike = false
fd_thres = 0.2
fd_radius = 50
fft_spikes_detector = false
headmask = "BET"
ica = false
species = "human"
template_id = "MNI152NLin2009cAsym"

[nipype]
crashfile_format = "txt"
get_linked_libs = false
local_hash_check = true
nprocs = 1
omp_nthreads = 1
plugin = "MultiProc"
remove_node_directories = false
resource_monitor = false
stop_on_first_crash = true

[workflow.inputs]
T1w = [ "/home/joe/mriqc_space/sub-C001/anat/sub-C001_acq-MP2RAGE_run-01_T1w.nii.gz",]

[nipype.plugin_args]
maxtasksperchild = 1
raise_insufficient = false
